### ISSUE TITLE
Clojurescript in browser

### ISSUE THREAD

**Issue by nenadalm** [macchiato-framework/macchiato-template#10]
I started using macchiato with https://github.com/Day8/re-frame. I thought it would be nice if the template supported clojurescript in browser? (It can be framework/library agnostic - just single `app.cljs` file with `project.clj` preconfigured to work nicely).

Would you be interested in this if I sent some pr? Or should I create my own template?

**Comment by yogthos** [comment]
a pr sounds great. I've been using flags in the [luminus template](https://github.com/luminus-framework/luminus-template) for different features, so maybe we could use the same approach here.
