### ISSUE TITLE
about the cluster handling code

### ISSUE THREAD

**Issue by facundoolano** [macchiato-framework/macchiato-template#4]
Hey, I've been thinking a bit about the code in the core ns of the template and wonder if having the cluster handling functions there is a good idea. Right now half of the code in the core file is about clusters so you kind of imply "you need all this boilerplate if you want to spin up a server using Macchiato", which is not really true. Plus, for someone just approaching the library it's more parts you'll need to figure out and at least in my case that meant just treating that file like a black box for a while.

Another thing that I found a bit misleading was that despite the presence of that code, you won't be actually using it unless you add a config file and enable clusters, which isn't evident when you're starting out with the library.

I agree that more often than not you'll want to run your Node.js apps in a cluster, at least in production, but handling the cluster boilerplate yourself is not necessarily the best way to do it, since having master/worker processes is only half the story: you'll usually want to also benefit from graceful shutdowns, code reloads and dynamically scaling the amount of workers. [PM2](https://github.com/Unitech/pm2) is a tool that enables that without requiring any boilerplate, and I think that [recluster](https://github.com/doxout/recluster) and [naught](https://github.com/andrewrk/naught) achieve the same thing in a more programmatic way.

I imagine the decision to bake cluster code right in the template was about stressing the fact (specially for people coming from the JVM ecosystem) that this is Node.js and you are running code in a single thread so don't expect it to take advantage of all your cpu cores. But I'd rather put that knowledge in the documentation and one of the example projects instead of treating it as the default way to go. In my experience you'll just use PM2 unless you have more sophisticated requirements in which case you may use/write a tailored wrapper around the cluster module (for example [SocketCluster](https://github.com/SocketCluster/socketcluster) does that for web sockets).

**Comment by yogthos** [comment]
When I started the template I wasn't really familiar with the Node ecosystem, and clustering in the app seemed like a good idea. However, I agree that tools like PM2 are the proper way to handle that. I actually ended up using PM2 for a project recently and loved it.

So, I think removing that stuff from the template and adding documentation on proper clustering is the right way to go.

**Comment by yogthos** [comment]
This is actually great timing too @niquola just pushed a great looking docs site https://github.com/macchiato-framework/macchiato-framework.github.io/pull/1 so we could add a deployment section there and explain how to do clustering properly

**Comment by facundoolano** [comment]
Sent a PR to remove the cluster code from the template and filed an issue to remember to add the deployment section in the docs. Closing this.
