### ISSUE TITLE
Invalid hexadecimal escape sequence during project startup

### ISSUE THREAD

**Issue by clartaq** [macchiato-framework/macchiato-template#7]
Hi,

Just used the template to create a new project.

`lein new macchiato outliner`

Running `lein build` seemed to work fine. However, on trying to start the project with `npm start`, the following error cascade was produced:

```
C:\projects\outliner>npm start

> outliner@0.1.0-SNAPSHOT start C:\projects\outliner
> node target/out/outliner.js

C:\projects\outliner\target\out\cuerdas\regexp.js:4
cljs.core.load_file("target\out\xregexp\xregexp.js");
                               ^^^^
SyntaxError: Invalid hexadecimal escape sequence
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.CLOSURE_IMPORT_SCRIPT (C:\projects\outliner\target\out\goog\bootstrap\nodejs.js:75:5)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! outliner@0.1.0-SNAPSHOT start: `node target/out/outliner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the outliner@0.1.0-SNAPSHOT start script 'node target/out/outliner.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the outliner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node target/out/outliner.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs outliner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls outliner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\outliner\npm-debug.log
```

There was no error after building `lein package` and running.

Any help appreciated.

**Comment by clartaq** [comment]
Looking for a workaround, I tried building and running under the Linux Subsystem for Windows. Unfortunately, Leiningen fails for the cljsbuild, doo, figwheel, and leiningen.npm tasks. Not sure why.

**Comment by yogthos** [comment]
I don't use Windows myself, but looks like a bug in NPM. You could try see if it's at the latest version and upgrade if not.

**Comment by clartaq** [comment]
I upgraded nodejs and npm from the latest LTS releases to the latest feature releases (8.3.0 and 5.3.0 respectively). Building and starting again produced the same error.

Looking in the `target\out\cuerdas\regexp.js` file, it starts off like this:

```clojure
// Compiled by ClojureScript 1.9.854 {:target :nodejs}
goog.provide('cuerdas.regexp');
goog.require('cljs.core');
cljs.core.load_file("target\out\xregexp\xregexp.js");
goog.require('goog.string');
cuerdas.regexp.xregexp = XRegExp;

```
I believe `macchiato-core` pulls in the `funcool/cuerdas`, which for ClojureScript, pulls in the stuff in the `xregexp.js` dependency. Is that correct?

I can hand-edit the `target\out\cuerdas\regexp.js` file and run the program correctly. Of course, the next time I make a change in the source of my program, the file gets recompiled with the erroneous file path again.

Does this seem like an NPM error? Not sure what is so special about this library that it gets messed up while none of the others do.

**Comment by yogthos** [comment]
It might be a Windows specific bug in the cuerdas library as well. You could try tweaking the code [here](https://github.com/funcool/cuerdas/blob/master/src/cuerdas/regexp.cljc), and then install a local copy by running `lein install` to test.

**Comment by bissonex** [comment]
This commit (https://github.com/clojure/clojurescript/commit/b74538b4e9947973175cf197704c18b10a5ce6bf) fixes the issue in release (https://github.com/clojure/clojurescript/releases/tag/r1.9.946)
